# Generated by Django 4.2.15 on 2024-08-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category_images/default.jpg', upload_to='category_images/'),
        ),
    ]
